#name: Build and Test
#
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#
#jobs:
#  test:
#    runs-on: ubuntu-latest

#    steps:
#      - name: Checkout código
#        uses: actions/checkout@v3
#
#      - name: Configurar JDK 21 (Amazon Corretto)
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'corretto'
#          java-version: '21'
#          cache: maven
#
#      - name: Build e Testes com cobertura
#        run: mvn clean verify
#
#      - name: Armazenar relatório JaCoCo
#        uses: actions/upload-artifact@v4
#        with:
#          name: jacoco-report
#          path: target/site/jacoco
